// app/layout.js
import { Inter } from "next/font/google";
import "./globals.css";
import MyNavbar from "@/app/components/MyNavbar";
import FilterColumn from "@/app/components/FilterColumn";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <MyNavbar />
        <div className="flex">
            <aside className="w-64 p-4">
                <FilterColumn />
            </aside>
            <main className="flex-1 p-4">
                {children}
            </main>
        </div>
        </body>
        </html>
    );
}
